#!/usr/bin/env node
import fs from "node:fs";
import http from "node:http";
import path from "node:path";
import { fileURLToPath } from "node:url";

function readDotEnv(cwd) { const values = {}; const files = [...new Set([path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", ".env"), path.resolve(cwd, ".env")])]; for (const file of files) { try { for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) { const t = line.trim(), i = t.indexOf("="); if (!t || t.startsWith("#") || i < 0) continue; const key = t.slice(0, i).trim(); let value = t.slice(i + 1).trim(); if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1); if (key && values[key] === undefined) values[key] = value; } } catch {} } return values; }
function textOf(message) { if (message?.role !== "assistant" || !Array.isArray(message.content)) return ""; return message.content.filter((p) => p?.type === "text").map((p) => p.text || "").join("").trim(); }
function post(urlValue, body, token) { const url = new URL(urlValue), payload = JSON.stringify(body), transport = url.protocol === "https:" ? import("node:https") : import("node:http"); return transport.then((module) => new Promise((resolve, reject) => { const request = module.request(url, { method: "POST", headers: { authorization: `Bearer ${token}`, "content-type": "application/json", "content-length": Buffer.byteLength(payload) } }, (response) => { let raw = ""; response.setEncoding("utf8"); response.on("data", (c) => { raw += c; }); response.on("end", () => resolve({ status: response.statusCode || 0, raw })); }); request.setTimeout(15000, () => request.destroy(new Error("webhook request timed out"))); request.on("error", reject); request.end(payload); })); }
async function mirror(message, settings) { const response = await post(settings.url, { to: settings.to, message }, settings.token); if (response.status < 200 || response.status >= 300) throw new Error(response.raw || `HTTP ${response.status}`); }
function readJson(req) { return new Promise((resolve, reject) => { let body = ""; req.setEncoding("utf8"); req.on("data", (c) => { body += c; if (body.length > 1024 * 1024) reject(new Error("request body is too large")); }); req.on("end", () => { try { resolve(JSON.parse(body || "{}")); } catch { reject(new Error("request body must be valid JSON")); } }); req.on("error", reject); }); }
export default function telegramMirror(pi) { let settings; let server; const seen = new Set(); const get = (cwd) => { if (settings) return settings; const env = { ...readDotEnv(cwd), ...process.env }; settings = { url: env.PI_TELEGRAM_WEBHOOK_URL || env.TELEGRAM_WEBHOOK_URL || `http://${env.TELEGRAM_HOST || "127.0.0.1"}:${env.TELEGRAM_PORT || "3093"}/webhook`, token: env.PI_TELEGRAM_WEBHOOK_TOKEN || env.TELEGRAM_WEBHOOK_TOKEN || env.WEBHOOK_TOKEN || "", to: env.PI_TELEGRAM_TO || env.TELEGRAM_TO || "", inboundHost: env.PI_TELEGRAM_INBOUND_HOST || "127.0.0.1", inboundPort: Number(env.PI_TELEGRAM_INBOUND_PORT || "3094"), inboundPath: env.PI_TELEGRAM_INBOUND_PATH || "/telegram/inbound", inboundToken: env.PI_TELEGRAM_INBOUND_TOKEN || env.INBOUND_WEBHOOK_TOKEN || "" }; return settings; };
  pi.on("session_start", (_event, ctx) => { const s = get(ctx.cwd); if (!s.inboundToken) return ctx.ui.notify("Telegram inbound is disabled: set PI_TELEGRAM_INBOUND_TOKEN or INBOUND_WEBHOOK_TOKEN", "warning"); server = http.createServer(async (req, res) => { const url = new URL(req.url || "/", `http://${s.inboundHost}`); if (req.method !== "POST" || url.pathname !== s.inboundPath) { res.writeHead(404); return res.end(); } const auth = String(req.headers.authorization || ""); const token = auth.startsWith("Bearer ") ? auth.slice(7) : String(req.headers["x-webhook-token"] || ""); if (token !== s.inboundToken) { res.writeHead(401); return res.end(); } try { const message = await readJson(req); if (message.messageId && seen.has(message.messageId)) return res.end('{"ok":true}'); if (message.messageId) seen.add(message.messageId); if (!message.body?.trim()) throw new Error("body is required"); await pi.sendUserMessage(`[Telegram ${message.senderId || message.chatId || "unknown"}]\n${message.body}`, { deliverAs: "followUp" }); res.end('{"ok":true}'); } catch (e) { res.writeHead(400, { "content-type": "application/json" }); res.end(JSON.stringify({ ok: false, error: e.message })); } }); server.listen(s.inboundPort, s.inboundHost, () => ctx.ui.notify(`Telegram inbound listener: http://${s.inboundHost}:${s.inboundPort}${s.inboundPath}`)); });
  pi.on("session_shutdown", () => { server?.close(); server = undefined; });
  pi.on("message_end", (event, ctx) => { const message = textOf(event.message), s = get(ctx.cwd); if (!message) return; if (!s.to || !s.token) return ctx.ui.notify("Telegram mirror is not configured: set PI_TELEGRAM_TO and PI_TELEGRAM_WEBHOOK_TOKEN", "warning"); void mirror(message, s).catch((e) => ctx.ui.notify(`Telegram mirror failed: ${e.message}`, "error")); });
}
export { textOf, textOf as getText, mirror };
